### ISSUE TITLE
On 8.5.1 (PRO), jekyll errors with:  jekyll 3.8.6 | Error:  key{attrs} not found

### ISSUE THREAD

**Issue by funkypenguin** [hydecorp/hydejack#173]
Hi guys,

I tried to upgrade to 8.5.1 (PRO), by copying the contents of `upgrade/` on top of my existing 8.3 installation.

However, when I run `bundle exec jekyll serve`, I get the following:

```
[funkypenguin:~/Documents/Personal/Projects/blog] 0.8.3(+1261/-611)+* ± bundle exec jekyll serve
Configuration file: /Users/funkypenguin/Documents/Personal/Projects/blog/_config.yml
/Users/funkypenguin/Documents/Personal/Projects/blog/_plugins/jekyll-replace-imgs/jekyll-replace-imgs.rb:24: warning: already initialized constant RE_IMG
/Library/Ruby/Gems/2.3.0/gems/jekyll-replace-img-0.4.0/lib/jekyll-replace-img/hooks.rb:9: warning: previous definition of RE_IMG was here
/Users/funkypenguin/Documents/Personal/Projects/blog/_plugins/jekyll-replace-imgs/jekyll-replace-imgs.rb:25: warning: already initialized constant RE_DATAURL
/Library/Ruby/Gems/2.3.0/gems/jekyll-replace-img-0.4.0/lib/jekyll-replace-img/hooks.rb:16: warning: previous definition of RE_DATAURL was here
/Users/funkypenguin/Documents/Personal/Projects/blog/_plugins/jekyll-replace-imgs/jekyll-replace-imgs.rb:26: warning: already initialized constant RE_IGNORE
/Library/Ruby/Gems/2.3.0/gems/jekyll-replace-img-0.4.0/lib/jekyll-replace-img/hooks.rb:10: warning: previous definition of RE_IGNORE was here
/Users/funkypenguin/Documents/Personal/Projects/blog/_plugins/jekyll-replace-imgs/jekyll-replace-imgs.rb:28: warning: already initialized constant REPLACEMENT
/Library/Ruby/Gems/2.3.0/gems/jekyll-replace-img-0.4.0/lib/jekyll-replace-img/hooks.rb:11: warning: previous definition of REPLACEMENT was here
/Library/Ruby/Gems/2.3.0/gems/jekyll-replace-img-0.4.0/lib/jekyll-replace-img/hooks.rb:25: warning: flags ignored
/Library/Ruby/Gems/2.3.0/gems/jekyll-replace-img-0.4.0/lib/jekyll-replace-img/hooks.rb:30: warning: flags ignored
            Source: /Users/funkypenguin/Documents/Personal/Projects/blog
       Destination: /Users/funkypenguin/Documents/Personal/Projects/blog/_site
 Incremental build: disabled. Enable with --incremental
      Generating...
       Jekyll Feed: Generating feed for posts
jekyll 3.8.6 | Error:  key{attrs} not found
```

Any ideas re what I missed?

Thanks!
D

**Comment by qwtel** [comment]
ah interesting. try deleting/renaming _plugins folder. please let me know if it works.

**Comment by funkypenguin** [comment]
That worked, yes. In fact, only removing `_plugins/jekyll-replace-imgs` worked too :)

**Comment by qwtel** [comment]
Great! Can you confirm that you've also upgraded `Gemfile` and/or `_config.yml`? This should not happen otherwise.

**Comment by shawnyeager** [comment]
I'm seeing the same problem, both locally and when attempting to build on Netlify.

**Comment by shawnyeager** [comment]
@qwtel I followed your suggestion to delete `_plugins`, which fixed the problem locally. However, on Netlify, the build fails as follows:

```
5:39:43 PM: Build ready to start
5:39:46 PM: build-image version: 9e0f207a27642d0115b1ca97cd5e8cebbe492f63
5:39:46 PM: build-image tag: v3.3.2
5:39:46 PM: buildbot version: ef8d0929ed0baabafd8bbb7d0b021e1fc24180c0
5:39:46 PM: Fetching cached dependencies
5:39:46 PM: Starting to download cache of 243.1MB
5:39:48 PM: Finished downloading cache in 2.139531361s
5:39:48 PM: Starting to extract cache
5:39:58 PM: Finished extracting cache in 9.425434421s
5:39:58 PM: Finished fetching cache in 11.712178776s
5:39:58 PM: Starting to prepare the repo for build
5:39:58 PM: Preparing Git Reference refs/heads/8.5.1
5:40:01 PM: Starting build script
5:40:01 PM: Installing dependencies
5:40:02 PM: Started restoring cached node version
5:40:04 PM: Finished restoring cached node version
5:40:05 PM: v8.16.1 is already installed.
5:40:07 PM: Now using node v8.16.1 (npm v6.4.1)
5:40:07 PM: Attempting ruby version 2.6.2, read from .ruby-version file
5:40:09 PM: Using ruby version 2.6.2
5:40:09 PM: Using PHP version 5.6
5:40:09 PM: Started restoring cached ruby gems
5:40:09 PM: Finished restoring cached ruby gems
5:40:09 PM: Installing gem bundle
5:40:12 PM: Fetching gem metadata from https://rubygems.org/
5:40:12 PM: .
5:40:12 PM: .
5:40:13 PM: .
5:40:13 PM: .
5:40:13 PM: .
5:40:13 PM: .
5:40:14 PM: .
5:40:14 PM: .
5:40:14 PM: .
5:40:14 PM: .
5:40:14 PM: .
5:40:15 PM: Fetching gem metadata from https://rubygems.org/
5:40:15 PM: .
5:40:15 PM: Resolving dependencies...
5:40:15 PM: Using public_suffix 3.1.1
5:40:15 PM: Using addressable 2.6.0
5:40:15 PM: Using bundler 2.0.1
5:40:15 PM: Using colorator 1.1.0
5:40:15 PM: Using concurrent-ruby 1.1.5
5:40:15 PM: Using eventmachine 1.2.7
5:40:15 PM: Using http_parser.rb 0.6.0
5:40:15 PM: Using em-websocket 0.5.1
5:40:15 PM: Using ffi 1.11.1
5:40:15 PM: Using forwardable-extended 2.6.0
5:40:15 PM: Using i18n 0.9.5
5:40:15 PM: Using rb-fsevent 0.10.3
5:40:15 PM: Using rb-inotify 0.10.0
5:40:15 PM: Using sass-listen 4.0.0
5:40:15 PM: Using sass 3.7.4
5:40:15 PM: Using jekyll-sass-converter 1.5.2
5:40:15 PM: Using ruby_dep 1.5.0
5:40:15 PM: Using listen 3.1.5
5:40:15 PM: Using jekyll-watch 2.2.1
5:40:15 PM: Using kramdown 1.17.0
5:40:15 PM: Using liquid 4.0.3
5:40:15 PM: Using mercenary 0.3.6
5:40:15 PM: Using pathutil 0.16.2
5:40:15 PM: Fetching rouge 3.9.0
5:40:15 PM: Installing rouge 3.9.0
5:40:16 PM: Using safe_yaml 1.0.5
5:40:16 PM: Using jekyll 3.8.6
5:40:16 PM: Using jekyll-default-layout 0.1.4
5:40:16 PM: Using jekyll-feed 0.12.1
5:40:16 PM: Using jekyll-optional-front-matter 0.3.0
5:40:16 PM: Using jekyll-paginate 1.1.0
5:40:16 PM: Using jekyll-readme-index 0.2.0
5:40:16 PM: Using jekyll-redirect-from 0.15.0
5:40:16 PM: Using jekyll-relative-links 0.6.0
5:40:16 PM: Fetching jekyll-replace-img 0.4.0
5:40:16 PM: Installing jekyll-replace-img 0.4.0
5:40:16 PM: Using jekyll-seo-tag 2.6.1
5:40:16 PM: Using jekyll-sitemap 1.3.1
5:40:16 PM: Using jekyll-titles-from-headings 0.5.1
5:40:16 PM: Bundle complete! 12 Gemfile dependencies, 37 gems now installed.
5:40:16 PM: Bundled gems are installed into `/opt/build/cache/bundle`
5:40:17 PM: Gem bundle installed
5:40:17 PM: Started restoring cached go cache
5:40:18 PM: Finished restoring cached go cache
5:40:18 PM: Installing Go version 1.10
5:40:19 PM: unset GOOS;
5:40:19 PM: unset GOARCH;
5:40:19 PM: export GOROOT='/opt/buildhome/.gimme_cache/versions/go1.10.linux.amd64';
5:40:19 PM: export PATH="/opt/buildhome/.gimme_cache/versions/go1.10.linux.amd64/bin:${PATH}";
5:40:19 PM: go version >&2;
5:40:19 PM: export GIMME_ENV='/opt/buildhome/.gimme_cache/env/go1.10.linux.amd64.env';
5:40:19 PM: go version go1.10 linux/amd64
5:40:19 PM: Installing missing commands
5:40:19 PM: Verify run directory
5:40:19 PM: Executing user command: jekyll build
5:40:19 PM: Configuration file: /opt/build/repo/_config.yml
5:40:19 PM: /opt/build/repo/_plugins/jekyll-replace-imgs/jekyll-replace-imgs.rb:24: warning: already initialized constant RE_IMG
5:40:19 PM: /opt/build/cache/bundle/ruby/2.6.0/gems/jekyll-replace-img-0.4.0/lib/jekyll-replace-img/hooks.rb:9: warning: previous definition of RE_IMG was here
5:40:19 PM: /opt/build/repo/_plugins/jekyll-replace-imgs/jekyll-replace-imgs.rb:25: warning: already initialized constant RE_DATAURL
5:40:19 PM: /opt/build/cache/bundle/ruby/2.6.0/gems/jekyll-replace-img-0.4.0/lib/jekyll-replace-img/hooks.rb:16: warning: previous definition of RE_DATAURL was here
5:40:19 PM: /opt/build/repo/_plugins/jekyll-replace-imgs/jekyll-replace-imgs.rb:26: warning: already initialized constant RE_IGNORE
5:40:19 PM: /opt/build/cache/bundle/ruby/2.6.0/gems/jekyll-replace-img-0.4.0/lib/jekyll-replace-img/hooks.rb:10: warning: previous definition of RE_IGNORE was here
5:40:19 PM: /opt/build/repo/_plugins/jekyll-replace-imgs/jekyll-replace-imgs.rb:28: warning: already initialized constant REPLACEMENT
5:40:19 PM: /opt/build/cache/bundle/ruby/2.6.0/gems/jekyll-replace-img-0.4.0/lib/jekyll-replace-img/hooks.rb:11: warning: previous definition of REPLACEMENT was here
5:40:19 PM: /opt/build/cache/bundle/ruby/2.6.0/gems/jekyll-replace-img-0.4.0/lib/jekyll-replace-img/hooks.rb:25: warning: flags ignored
5:40:19 PM: /opt/build/cache/bundle/ruby/2.6.0/gems/jekyll-replace-img-0.4.0/lib/jekyll-replace-img/hooks.rb:30: warning: flags ignored
5:40:19 PM:             Source: /opt/build/repo
5:40:19 PM:        Destination: /opt/build/repo/_site
5:40:19 PM:  Incremental build: disabled. Enable with --incremental
5:40:19 PM:       Generating...
5:40:20 PM:        Jekyll Feed: Generating feed for posts
5:40:20 PM: jekyll 3.8.6 | Error:  key{attrs} not found
5:40:20 PM: Skipping functions preparation step: no functions directory set
5:40:20 PM: Caching artifacts
5:40:20 PM: Started saving ruby gems
5:40:20 PM: Finished saving ruby gems
5:40:20 PM: Started saving pip cache
5:40:20 PM: Finished saving pip cache
5:40:20 PM: Started saving emacs cask dependencies
5:40:21 PM: Finished saving emacs cask dependencies
5:40:21 PM: Started saving maven dependencies
5:40:21 PM: Finished saving maven dependencies
5:40:21 PM: Started saving boot dependencies
5:40:21 PM: Finished saving boot dependencies
5:40:21 PM: Started saving go dependencies
5:40:23 PM: Finished saving go dependencies
5:40:23 PM: Error running command: Build script returned non-zero exit code: 1
5:40:23 PM: Failing build: Failed to build site
5:40:23 PM: failed during stage 'building site': Build script returned non-zero exit code: 1
5:40:23 PM: Finished processing build request in 36.950759231s
```

**Comment by shawnyeager** [comment]
One more update to the above: after commenting out references to `jekyll-replace-img` in `Gemfile` and `_config.yml`, the Netlify build completes successfully.

**Comment by qwtel** [comment]
This should be fixed by upgrading `jekyll-replace-img` to 0.5.0 (run `bundle update`)

**Comment by funkypenguin** [comment]
The issue is fixed locally, but I too have the issue @shawnyeager has in Netlify, with:

```
8:57:52 PM: Finished saving go dependencies
8:57:52 PM: Error running command: Build script returned non-zero exit code: 1
8:57:52 PM: Failing build: Failed to build site
8:57:52 PM: failed during stage 'building site': Build script returned non-zero exit code: 1
8:57:52 PM: Finished processing build request in 1m36.414257525s
```

**Comment by shawnyeager** [comment]
@qwtel I updated the gem to 0.5.0, but the Netlify build still fails with `jekyll 3.8.6 | Error:  can't modify frozen String`.

**Comment by qwtel** [comment]
I can no longer reproduce this with 0.5.0. I suspect that this is not working for the same reason deleting `_plugins` didn't work — there must be some kind of caching at some level.

**Comment by shawnyeager** [comment]
For what it's worth, I used Netlify's "Clear cache and deploy site" option to produce the above deploy log, so theoretically, no caching.

**Comment by qwtel** [comment]
> For what it's worth, I used Netlify's "Clear cache and deploy site" option to produce the above deploy log, so theoretically, no caching.

Somehow updating to 0.5.0 didn't work. From your log

    12:14:59 PM: Fetching jekyll-replace-img 0.4.0
    12:14:59 PM: Installing jekyll-replace-img 0.4.0

I'll release a new verison with the dependecy updated. But that will only resolve the build failure. Using both the `_plugins` and gem version of replace-img simultaneously can lead to more subtle bugs.

**Comment by shawnyeager** [comment]
Thanks. I’d missed that. And understood regarding `_plugins`. I’ve deleted. 

If helpful, I pushed a commit with `Gemfile.lock` removed to see how the Netlify build would go, and see this:

```
10:24:47 AM: Executing user command: jekyll build
10:24:47 AM: /opt/buildhome/.rvm/rubies/ruby-2.6.2/lib/ruby/2.6.0/bundler/resolver.rb:287:in `block in verify_gemfile_dependencies_are_found!': Could not find gem 'jekyll-replace-img' in any of the gem sources listed in your Gemfile. (Bundler::GemNotFound)
```
